development:
  adapter: mysql
  database: activeplaces_development
  username: root

test:
  adapter: mysql
  database: activeplaces_test
  username: root

production:
  adapter: mysql
  database: activeplaces_production
  username: root