development:
  adapter: mysql
  database: activeplaces_dev
  username: root
  password: t3nd3r
  
test:
  adapter: mysql
  database: activeplaces_test
  username: root

production:
  adapter: mysql
  database: activeplaces_production
  username: root